import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {},
  hi: {
    // Nav & Sidebar
    'Dashboard': 'डैशबोर्ड',
    'EVM Inventory': 'ईवीएम इन्वेंटरी',
    'Send EVM Batch': 'ईवीएम बैच भेजें',
    'Receive EVM Units': 'ईवीएम इकाइयां प्राप्त करें',
    'User Management': 'उपयोगकर्ता प्रबंधन',
    'Reports & Analytics': 'रिपोर्ट और विश्लेषण',
    'Search EVM Units': 'ईवीएम इकाइयां खोजें',
    'Activity Logs': 'गतिविधि लॉग',
    'Logout Panel': 'लॉगआउट पैनल',

    // Headers & Titles
    'Dashboard Overview': 'डैशबोर्ड अवलोकन',
    'EVM Inventory System': 'ईवीएम इन्वेंटरी प्रणाली',
    'Register EVM': 'ईवीएम पंजीकृत करें',
    'Pending Receivables': 'लंबित प्राप्तियां',
    'User Account Control': 'उपयोगकर्ता खाता नियंत्रण',
    'System Activity Logs': 'सिस्टम गतिविधि लॉग',
    'User Account Control System': 'उपयोगकर्ता खाता नियंत्रण प्रणाली',

    // User Page UI
    'User Code': 'उपयोगकर्ता कोड',
    'Full Name': 'पूरा नाम',
    'Role': 'भूमिका',
    'Jurisdiction': 'अधिकार क्षेत्र',
    'Type': 'प्रकार',
    'Account Status': 'खाता स्थिति',
    'Last Login': 'अंतिम लॉगिन',
    'Actions': 'कार्रवाई',
    'Create Officer Account': 'अधिकारी खाता बनाएं',
    'Reset Filters': 'फ़िल्टर रीसेट करें',
    'Filter Users': 'उपयोगकर्ता फ़िल्टर करें',
    'Search Users': 'उपयोगकर्ता खोजें',
    'Search User ID or Name...': 'उपयोगकर्ता आईडी या नाम खोजें...',
    'State': 'राज्य',
    'District': 'जिला',
    'Role type': 'भूमिका प्रकार',
    'All Roles': 'सभी भूमिकाएं',
    'All States': 'सभी राज्य',
    'All Statuses': 'सभी स्थितियां',
    'Choose District': 'जिला चुनें',
    'Select State First': 'पहले राज्य चुनें',
    'Save Modifications': 'संशोधन सहेजें',
    'Cancel': 'रद्द करें',
    'Security Password': 'सुरक्षा पासवर्ड',
    'Password': 'पासवर्ड',
    'Sign In': 'साइन इन',
    'Confirm Password': 'पासवर्ड की पुष्टि करें',
    'Confirm New Password': 'नए पासवर्ड की पुष्टि करें',
    'Officer Role Type': 'अधिकारी भूमिका प्रकार',
    'Username': 'उपयोगकर्ता नाम',
    'State Jurisdictional Allocation': 'राज्य क्षेत्राधिकार आवंटन',
    'District Allocation': 'जिला आवंटन',
    'Officer Full Name': 'अधिकारी का पूरा नाम',
    'Edit Account': 'खाता संपादित करें',
    'Save': 'सहेजें',
    'Confirm Action': 'कार्रवाई की पुष्टि करें',
    'Confirm': 'पुष्टि करें',
    'Active': 'सक्रिय',
    'Inactive': 'निष्क्रिय',
    'State Officer': 'राज्य अधिकारी',
    'District Officer': 'जिला अधिकारी',
    'Permanent': 'स्थायी',
    'Temporary': 'अस्थायी',
    'Active Accounts': 'सक्रिय खाते',
    'Deactivated Accounts': 'निष्क्रिय खाते',
    'Search': 'खोजें',

    // Dashboard UI additions
    'System Dashboard': 'सिस्टम डैशबोर्ड',
    'Logged in as': 'के रूप में लॉग इन किया',
    'Sync Data': 'डेटा सिंक करें',
    'Synchronizing systems...': 'सिस्टम सिंक्रनाइज़ किया जा रहा है...',
    'Loading EVM database...': 'ईवीएम डेटाबेस लोड किया जा रहा है...',
    'System Sync Failure': 'सिस्टम सिंक विफलता',
    'Failed to fetch database information. Ensure the backend server is running and database schema is seeded.': 'डेटाबेस जानकारी प्राप्त करने में विफल। सुनिश्चित करें कि बैकएंड सर्वर चल रहा है और डेटाबेस स्कीमा सीडेड है।',
    'Retry Sync': 'पुनः सिंक करें',
    'Total EVM Units': 'कुल ईवीएम इकाइयां',
    'In Transit': 'पारगमन में',
    'Currently moving between warehouses': 'वर्तमान में गोदामों के बीच स्थानांतरित',
    'No movements': 'कोई हलचल नहीं',
    'moving': 'गतिमान',
    'flagged': 'चिह्नित',
    '0 flagged': '0 चिह्नित',
    'Deployed Units': 'तैनात इकाइयां',
    'Installed at active polling booths': 'सक्रिय मतदान केंद्रों पर स्थापित',
    'Active booths': 'सक्रिय मतदान केंद्र',
    'Faulty / Repair': 'दोषपूर्ण / मरम्मत',
    'Reported damaged/faulty units': 'क्षतिग्रस्त/दोषपूर्ण इकाइयां',
    'EVM Operations panel': 'ईवीएम संचालन पैनल',
    'Dispatch Consignment': 'शिपमेंट भेजें',
    'Confirm Receipt': 'प्राप्ति की पुष्टि करें',
    'Initiate a new physical transfer of units to another state or district warehouse.': 'दूसरे राज्य या जिले के गोदाम में इकाइयों का भौतिक स्थानांतरण शुरू करें।',
    'New Dispatch': 'नया डिस्पैच',
    'Scan and register incoming units sent to your location. Check conditions on receipt.': 'अपने स्थान पर आने वाली इकाइयों को स्कैन और पंजीकृत करें। प्राप्त होने पर स्थिति की जाँच करें।',
    'Inventory Catalog': 'इन्वेंटरी सूची',
    'View allocation charts, search barcodes/QR codes, and inspect unit movement history.': 'आवंटन चार्ट देखें, बारकोड/क्यूआर कोड खोजें, और इकाइयों के इतिहास का निरीक्षण करें।',
    'View Inventory': 'इन्वेंटरी देखें',
    'Recent Dispatch Batches': 'हाल के डिस्पैच बैच',
    'View Logs': 'लॉग देखें',
    'Batch Code': 'बैच कोड',
    'From Location': 'प्रेषक स्थान',
    'To Destination': 'प्राप्तकर्ता स्थान',
    'Units': 'इकाइयां',
    'Dispatch Date': 'भेजने की तिथि',
    'Status': 'स्थिति',
    'Pending Incoming Shipments': 'लंबित आने वाले शिपमेंट',
    'Pending Incoming Consignments': 'लंबित आने वाले शिपमेंट',
    'There are': 'कुल',
    'batch(es) of EVM units currently in transit destined for your district or state. Review and process their receipt immediately upon physical arrival.': 'बैच ईवीएम इकाइयां आपके जिले या राज्य के लिए पारगमन में हैं। भौतिक आगमन पर तुरंत समीक्षा और प्राप्ति दर्ज करें।',
    'Go to Receipt Panel': 'प्राप्ति पैनल पर जाएं',
    'Origin': 'उत्पत्ति',
    'Sent': 'भेजा गया',
    'And': 'और',
    'more. View All': 'अधिक। सभी देखें',
    'EVM Allocation by State': 'राज्यवार ईवीएम आवंटन',
    'No state allocation data available.': 'कोई राज्य आवंटन डेटा उपलब्ध नहीं है।',
    'EVM Inventory Status Allocation': 'ईवीएम इन्वेंटरी स्थिति आवंटन',
    'No status distribution data available.': 'कोई स्थिति आवंटन डेटा उपलब्ध नहीं है।',
    'In Warehouse': 'गोदाम में',
    'Deployed (Polling)': 'तैनात (मतदान)',
    'CU': 'कंट्रोल यूनिट (CU)',
    'BU': 'बैलेट यूनिट (BU)',
    'VVPAT': 'वीवीपीएटी (VVPAT)',
    'CU:': 'कंट्रोल यूनिट (CU):',
    'BU:': 'बैलेट यूनिट (BU):',
    'VVPATs': 'वीवीपीएटी (VVPAT)',

    // EVM List UI

    'Unit Code': 'इकाई कोड',
    'Manufacturer': 'निर्माता',
    'Serial Number': 'क्रम संख्या',
    'Current Location': 'वर्तमान स्थान',
    'Device Category Type': 'डिवाइस श्रेणी प्रकार',
    'Manufacturer Corporation': 'निर्माता निगम',
    'Manufacturing Year': 'निर्माण वर्ष',
    'Unit Serial Number': 'इकाई क्रम संख्या',
    'Initial Warehouse / Storage Details': 'प्रारंभिक गोदाम / भंडारण विवरण',
    'Register & Save Unit': 'इकाई पंजीकृत और सहेजें',
    'ECI Headquarters': 'ईसीआई मुख्यालय',
    'Central Headquarters': 'केंद्रीय मुख्यालय',
    'Government of India — Secure EVM Tracking portal.': 'भारत सरकार — सुरक्षित ईवीएम ट्रैकिंग पोर्टल।',
    'Access is audited. Unauthorized entries will be prosecuted under federal cyber security laws.': 'पहुंच का ऑडिट किया जाता है। अनधिकृत प्रवेशों पर संघीय साइबर सुरक्षा कानूनों के तहत मुकदमा चलाया जाएगा।',
    'Officer User ID (User Code)': 'अधिकारी उपयोगकर्ता आईडी (उपयोगकर्ता कोड)',
    'Remember this session': 'इस सत्र को याद रखें',
    'Verify & Authenticate': 'सत्यापित करें और प्रमाणित करें',
    'EVM Lifecycle Management': 'ईवीएम जीवनचक्र प्रबंधन',
    'EVM Inventory Management system': 'ईवीएम इन्वेंटरी प्रबंधन प्रणाली',
    'Election Commission of India Portal': 'भारत निर्वाचन आयोग पोर्टल',
    'Madhya Pradesh State Election Commission': 'मध्य प्रदेश राज्य निर्वाचन आयोग',
    'Madhya Pradesh State Election Commission — EVM Inventory Management system': 'मध्य प्रदेश राज्य निर्वाचन आयोग — ईवीएम इन्वेंटरी प्रबंधन प्रणाली',
    'Authentication Failure:': 'प्रमाणीकरण विफलता:',
    'User ID must be at least 3 characters': 'उपयोगकर्ता आईडी कम से कम 3 वर्णों की होनी चाहिए',
    'Password must be at least 6 characters': 'पासवर्ड कम से कम 6 वर्णों का होना चाहिए',
    'Format: STATE_OFFICER_XX or DISTRICT_OFFICER_XX': 'प्रारूप: STATE_OFFICER_XX या DISTRICT_OFFICER_XX',
    'Secure Access Gateway': 'सुरक्षित पहुंच गेटवे',
    'EVM Barcode / QR Code': 'ईवीएम बारकोड / क्यूआर कोड',
    'Assigned Storage Box (Capacity 10)': 'आवंटित भंडारण बॉक्स (क्षमता 10)',
    'Warehouse location Description': 'गोदाम स्थान विवरण',
    'Register & Add to Shipment': 'पंजीकृत करें और शिपमेंट में जोड़ें',
    'Register & Add to consignment': 'पंजीकृत करें और शिपमेंट में जोड़ें',
    'EVM Barcode / QR Code (Unit Code)': 'ईवीएम बारकोड / क्यूआर कोड (इकाई कोड)',
    'Unique barcode/QR text scanned from physical device labels.': 'भौतिक डिवाइस लेबल से स्कैन किया गया अद्वितीय बारकोड/क्यूआर टेक्स्ट।',
    'Physical factory serial stamp number (e.g. S-39281)': 'भौतिक फ़ैक्टरी सीरियल स्टैंप नंबर (जैसे S-39281)',
    'E.g. Room A, Shelf 2 or North District Strongroom': 'जैसे कमरा ए, शेल्फ 2 या उत्तर जिला स्ट्रांगरूम',
    'EVM Main': 'ईवीएम मुख्य',
    'Inventory': 'इन्वेंटरी',
    'Dispatches': 'डिस्पैच',
    'Print Challan / Gate Pass': 'चालान / गेट पास प्रिंट करें',
    'Dispatch Another Batch': 'दूसरा बैच डिस्पैच करें',
    'Shipment Sent Successfully!': 'शिपमेंट सफलतापूर्वक भेज दिया गया!',
    'Consignment Consumed & Dispatched Successfully!': 'शिपमेंट सफलतापूर्वक भेज दिया गया!',
    'Expected Arrival': 'अपेक्षित आगमन',
    'Officer Remarks': 'अधिकारी की टिप्पणी',
    'Staged Inventory Summary': 'स्टेज की गई इन्वेंटरी का सारांश',
    'Control Units (CU):': 'नियंत्रण इकाइयां (CU):',
    'Ballot Units (BU):': 'मतपत्र इकाइयां (BU):',
    'VVPATs:': 'वीवीपीएटी (VVPAT):',
    'Total Units:': 'कुल इकाइयां:',
    'Shipment Details': 'शिपमेंट विवरण',
    'Consignment Details': 'शिपमेंट विवरण',
    'Shipping From': 'प्रेषक स्थान',
    'Shipping To': 'प्राप्तकर्ता स्थान',
    'Transit Remarks / Notes': 'पारगमन टिप्पणियां / नोट्स',
    'All Districts': 'सभी जिले',
    'Next: Destination': 'अगला: गंतव्य',
    'New Security Password': 'नया सुरक्षा पासवर्ड',
    'Leave empty to retain current password': 'वर्तमान पासवर्ड बनाए रखने के लिए खाली छोड़ें',
    'Edit Officer Account': 'अधिकारी खाता संपादित करें',
    'Save Changes': 'परिवर्तन सहेजें',
    'Create': 'बनाएं',
    'Clear All': 'सभी साफ करें',
    'Log Out': 'लॉग आउट',
    'Search results for': 'के लिए खोज परिणाम',
    'No results found': 'कोई परिणाम नहीं मिला',
    'Timestamp': 'समय',
    'Performed By': 'द्वारा संचालित',
    'Security Action': 'सुरक्षा कार्रवाई',
    'Entity Impacted': 'प्रभावित इकाई',
    'IP Address': 'आईपी पता',
    'Inspect Payload': 'पेलोड का निरीक्षण करें',

    // EVM statuses
    'IN_WAREHOUSE': 'गोदाम में',
    'IN_TRANSIT': 'पारगमन में',
    'DEPLOYED': 'तैनात किया गया',
    'FAULTY': 'दोषपूर्ण',
    'DECOMMISSIONED': 'सेवामुक्त',
    'RETURNED': 'लौटाया गया',

    // Unit categories
    'CONTROL_UNIT': 'नियंत्रण इकाई (CU)',
    'BALLOT_UNIT': 'मतपत्र इकाई (BU)',

    // Roles translation
    'ADMIN': 'सिस्टम व्यवस्थापक',
    'STATE_OFFICER': 'राज्य अधिकारी',
    'DISTRICT_OFFICER': 'जिला अधिकारी',
    'System Administrator': 'सिस्टम व्यवस्थापक',
    'STATE OFFICER': 'राज्य अधिकारी',
    'DISTRICT OFFICER': 'जिला अधिकारी',
    'Admin': 'व्यवस्थापक',
    'EVM': 'ईवीएम',
    'System': 'प्रणाली',
    'Secure Portal': 'सुरक्षित पोर्टल',

    // New translation gaps fixed
    'Connecting to EVM database...': 'ईवीएम डेटाबेस से कनेक्ट किया जा रहा है...',
    'Incoming Shipment Receipts': 'आने वाले शिपमेंट की रसीदें',
    'Incoming Consignment Receipts': 'आने वाले शिपमेंट की रसीदें',
    'Confirm and inspect device packages sent to your warehouse location.': 'अपने गोदाम के स्थान पर भेजे गए डिवाइस पैकेजों की पुष्टि और निरीक्षण करें।',
    'Acknowledge and inspect physical device packages sent to your warehouse custody.': 'अपने गोदाम के स्थान पर भेजे गए डिवाइस पैकेजों की पुष्टि और निरीक्षण करें।',
    'Refresh Shipments': 'शिपमेंट रीफ्रेश करें',
    'Refresh Consignments': 'शिपमेंट रीफ्रेश करें',
    'All Shipments Received': 'सभी शिपमेंट प्राप्त कर लिए गए',
    'All Shipments Acknowledged': 'सभी शिपमेंट प्राप्त कर लिए गए',
    'There are currently no pending in-transit batches allocated for your state or district warehouse location.': 'वर्तमान में आपके राज्य या जिले के गोदाम स्थान के लिए कोई लंबित पारगमन बैच आवंटित नहीं हैं।',
    'There are currently no pending in-transit batches allocated for your state or district warehouse custody.': 'वर्तमान में आपके राज्य या जिले के गोदाम स्थान के लिए कोई लंबित पारगमन बैच आवंटित नहीं हैं।',
    'Sent Date': 'भेजने की तिथि',
    'Items Quantity': 'आइटम मात्रा',
    'View Challan Details': 'चालान विवरण देखें',
    'Details': 'विवरण',
    'Confirm Shipment': 'शिपमेंट की पुष्टि करें',
    'Acknowledge Consignment': 'शिपमेंट की पुष्टि करें',
    'Shipping Origin': 'शिपिंग का स्रोत',
    'Dispatched Date': 'प्रेषण की तिथि',
    'Mark All Received': 'सभी को प्राप्त चिह्नित करें',
    'Mark All Missing': 'सभी को गायब चिह्नित करें',
    'Mark All Sealed Good': 'सभी को सील बंद सही चिह्नित करें',
    'Recd.': 'प्राप्त',
    'Condition on Receipt': 'प्राप्ति पर स्थिति',
    'Remarks': 'टिप्पणी',
    'E.g. Lock seal intact': 'जैसे लॉक सील बरकरार है',
    'Security Disclaimer': 'सुरक्षा अस्वीकरण',
    'Submitting receipt changes the status of successfully checked devices to IN_WAREHOUSE at your location. Missing units are locked immediately and flagged for investigation.': 'प्राप्ति जमा करने से आपके स्थान पर सफलतापूर्वक जाँचे गए उपकरणों की स्थिति गोदाम में (IN_WAREHOUSE) हो जाती है। गायब इकाइयों को तुरंत लॉक कर दिया जाता है और जाँच के लिए चिह्नित किया जाता है।',
    'Log Batch Receipt': 'बैच प्राप्ति दर्ज करें',
    'Good (Sealed)': 'अच्छा (सील बंद)',
    'Damaged (Broken Seal)': 'क्षतिग्रस्त (टूटी हुई सील)',
    'Faulty (Electronic Issue)': 'दोषपूर्ण (इलेक्ट्रॉनिक समस्या)',
    'Retrieving shipping details...': 'शिपिंग विवरण प्राप्त किया जा रहा है...',
    'Batch Record Not Found': 'बैच रिकॉर्ड नहीं मिला',
    'The requested dispatch batch or challan code does not exist in ECI records.': 'अनुरोधित डिस्पैच बैच या चालान कोड ईसीआई रिकॉर्ड में मौजूद नहीं है।',
    'Back to Dashboard': 'डैशबोर्ड पर वापस जाएं',
    'Sl No.': 'क्र.सं.',
    'Box Number': 'बॉक्स संख्या',
    'Not Received Yet': 'अभी तक प्राप्त नहीं हुआ',
    'MISSING': 'गायब',
    'Shipment Dispatch Details': 'शिपमेंट प्रेषण विवरण',
    'Consignment Dispatch Details': 'शिपमेंट प्रेषण विवरण',
    'Print Challan': 'चालान प्रिंट करें',
    'Cancel Shipment': 'शिपमेंट रद्द करें',
    'Cancel Consignment': 'शिपमेंट रद्द करें',
    'Shipping Summary': 'शिपिंग सारांश',
    'By': 'द्वारा',
    'Destination Warehouse': 'गंतव्य गोदाम',
    'Received by': 'द्वारा प्राप्त',
    'Timeline Details': 'समयरेखा विवरण',
    'Arrival': 'आगमन',
    'Custodian Remarks': 'कस्टोडियन की टिप्पणी',
    'Dispatched Device Items List': 'भेजे गए डिवाइस आइटमों की सूची',
    'Challan Details': 'चालान विवरण',
    'No Units Linked': 'कोई इकाई लिंक नहीं है',
    'This batch has no registered units. Check database integrity.': 'इस बैच में कोई पंजीकृत इकाइयां नहीं हैं। डेटाबेस अखंडता की जांच करें।',
    'Cancel Dispatch consignment': 'शिपमेंट रद्द करें',
    'Warning': 'चेतावनी',
    'Cancelling a shipment cannot be undone. All devices in this shipment will automatically return to the sender warehouse location.': 'शिपमेंट रद्द करना अपरिवर्तनीय है। सभी संबंधित डिवाइस (CU, BU, VVPAT) स्वचालित रूप से भेजने वाले गोदाम के स्थान पर वापस आ जाएंगे।',
    'Cancelling a consignment is irreversible. All associated devices (CUs, BUs, VVPATs) will be automatically returned to the shipping warehouse custody.': 'शिपमेंट रद्द करना अपरिवर्तनीय है। सभी संबंधित डिवाइस (CU, BU, VVPAT) स्वचालित रूप से भेजने वाले गोदाम के स्थान पर वापस आ जाएंगे।',
    'Cancellation Reason / Audit notes': 'रद्दीकरण का कारण / ऑडिट नोट्स',
    'E.g. Security convoy rescheduled, typo in destination warehouse state, etc.': 'जैसे सुरक्षा काफिला पुनर्निर्धारित, गंतव्य गोदाम राज्य में टाइपो, आदि।',
    'Back': 'पीछे',
    'Abort & Cancel Shipping Batch': 'प्रेषण रद्द करें और रोकें',
    'Register Scanned Device': 'स्कैन किए गए डिवाइस को पंजीकृत करें',
    'EVM Not Registered': 'ईवीएम पंजीकृत नहीं है',
    'was not found in the inventory system database. Please enter manufacturer details to add it now.': 'इन्वेंटरी सिस्टम डेटाबेस में नहीं मिला। कृपया इसे अभी जोड़ने के लिए निर्माता का विवरण दर्ज करें।',
    'Fetching device details and lifecycle history...': 'डिवाइस विवरण और जीवन चक्र इतिहास प्राप्त किया जा रहा है...',
    'Back to Inventory': 'इन्वेंटरी पर वापस जाएं',
    'Sync Device Details': 'डिवाइस विवरण सिंक करें',
    'No tracking events recorded.': 'कोई ट्रैकिंग इवेंट रिकॉर्ड नहीं किया गया।',
    'Audit inventory records, tracking histories, and logistics transaction logs.': 'इन्वेंटरी रिकॉर्ड, ट्रैकिंग इतिहास और लॉजिस्टिक्स लेनदेन लॉग का ऑडिट करें।',
    'Inventory Location': 'इन्वेंटरी स्थान',
    'Inventory Custody': 'इन्वेंटरी स्थान',
    'Dispatch History': 'डिस्पैच इतिहास',
    'Movement Timeline': 'आंदोलन समयरेखा',
    'State Location': 'राज्य स्थान',
    'District Location': 'जिला स्थान',
    'District Custody': 'जिला स्थान',
    'State Pool': 'राज्य पूल',
    'Inventory Location Summary Report': 'इन्वेंटरी स्थान सारांश रिपोर्ट',
    'Inventory Custody Summary Report': 'इन्वेंटरी स्थान सारांश रिपोर्ट',
    'Export CSV': 'सीएसवी निर्यात करें',
    'No Inventory Summaries Found': 'कोई इन्वेंटरी सारांश नहीं मिला',
    'Check if data has been registered or seeded in the database.': 'जांचें कि क्या डेटाबेस में डेटा पंजीकृत या सीड किया गया है।',
    'Origin Location': 'उत्पत्ति स्थान',
    'Units Quant': 'इकाइयों की मात्रा',
    'Shipment History Logs': 'शिपमेंट इतिहास लॉग',
    'Consignment Dispatch History Logs': 'शिपमेंट इतिहास लॉग',
    'Shipment Dispatch History Logs': 'शिपमेंट इतिहास लॉग',
    'No Dispatch History Logs Found': 'कोई डिस्पैच इतिहास लॉग नहीं मिला',
    'Log Date': 'लॉग तिथि',
    'Device Type': 'डिवाइस प्रकार',
    'Lifecycle Action': 'जीवनचक्र कार्रवाई',
    'Triggered By': 'द्वारा संचालित',
    'Device Movement Transaction Logs': 'डिवाइस आंदोलन लेनदेन लॉग',
    'No Movement Transaction Logs Recorded': 'कोई आंदोलन लेनदेन लॉग रिकॉर्ड नहीं किया गया',
    'Showing page': 'पेज दिखा रहा है',
    'of': 'का',
    'System Audit Trail Logs': 'सिस्टम ऑडिट ट्रेल लॉग',
    'Immutable log of all user logins, credential changes, registry modifications, and dispatches.': 'सभी उपयोगकर्ता लॉगिन, क्रेडेंशियल परिवर्तन, रजिस्ट्री संशोधन और डिस्पैच का अपरिवर्तनीय लॉग।',
    'Sync Log Files': 'लॉग फाइलें सिंक करें',
    'Filter Logs': 'लॉग फ़िल्टर करें',
    'Search Performed By (User ID/Name) or Entity ID...': 'द्वारा संचालित (उपयोगकर्ता आईडी/नाम) या इकाई आईडी खोजें...',
    'Log Action Type': 'लॉग कार्रवाई प्रकार',
    'All Log Actions': 'सभी लॉग कार्रवाइयाँ',
    'No Audit Logs Found': 'कोई ऑडिट लॉग नहीं मिला',
    'Try resetting your filters or checks systems connections.': 'अपने फ़िल्टर रीसेट करने का प्रयास करें या सिस्टम कनेक्शन की जाँच करें।',
    'Inspect Security Audit payload': 'सुरक्षा ऑडिट पेलोड का निरीक्षण करें',
    'Original State (Old Values)': 'मूल स्थिति (पुराने मूल्य)',
    'No original values captured (Create action)': 'कोई मूल मूल्य कैप्चर नहीं किया गया (निर्माण कार्रवाई)',
    'Modified State (New Values)': 'संशोधित स्थिति (नए मूल्य)',
    'No replacement values captured (Delete action)': 'कोई प्रतिस्थापन मूल्य कैप्चर नहीं किया गया (हटाने की कार्रवाई)',
    'Close Inspector': 'इंस्पेक्टर बंद करें',
    'Search Inventory': 'इन्वेंटरी खोजें',
    'View History': 'इतिहास देखें',

    // Officer modal strings
    'State Officer (Read/Write State)': 'राज्य अधिकारी (राज्य पढ़/लिखें)',
    'District Officer (Read/Write District)': 'जिला अधिकारी (जिला पढ़/लिखें)',
    'Unique login ID (e.g. MH_SO_01, USER_CENTRAL)': 'अद्वितीय लॉगिन आईडी (जैसे MH_SO_01, USER_CENTRAL)',
    'State officers bypass districts': 'राज्य अधिकारी जिला को बाईपास करते हैं',
    'Central ECI': 'केंद्रीय ईसीआई',
    'Role Assigned': 'भूमिका आवंटित',
    'Password Reset Option': 'पासवर्ड रीसेट विकल्प',
    'Leave both password fields blank unless you explicitly want to override the security credential password for this officer.': 'दोनों पासवर्ड फ़ील्ड खाली छोड़ें जब तक कि आप इस अधिकारी का सुरक्षा क्रेडेंशियल पासवर्ड बदलना न चाहें।',
    'Min 8 chars, 1 upper, 1 number, 1 special symbol.': 'न्यूनतम 8 अक्षर, 1 बड़ा अक्षर, 1 संख्या, 1 विशेष प्रतीक।',
    'Current Custody': 'वर्तमान स्थान',

    // Simplified terms
    'registered and added to consignment': 'पंजीकृत और शिपमेंट में जोड़ा गया',
    'registered and added to shipment': 'पंजीकृत और शिपमेंट में जोड़ा गया',
    'Loading consignment items from EVM database...': 'ईवीएम डेटाबेस से शिपमेंट आइटम लोड हो रहे हैं...',
    'Loading shipment items from EVM database...': 'ईवीएम डेटाबेस से शिपमेंट आइटम लोड हो रहे हैं...',
    'EVM Shipment Gate Pass': 'ईवीएम शिपमेंट गेट पास',
    'Consignment Dispatch Challan / Gate Pass': 'ईवीएम शिपमेंट गेट पास',
    'Inspect Activity Log Details': 'गतिविधि लॉग विवरण देखें',
    'Reports & Analytics Portal': 'रिपोर्ट और विश्लेषण पोर्टल',
    'Audit inventory records, tracking histories, and transaction logs.': 'इन्वेंटरी रिकॉर्ड, ट्रैकिंग इतिहास और लेनदेन लॉग का ऑडिट करें।',
    'Device Movement History Logs': 'डिवाइस आंदोलन इतिहास लॉग',
    'total logs': 'कुल लॉग',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('evm_language') || 'en';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('evm_language', lang);
  };

  const t = (key) => {
    if (!key) return '';
    if (language === 'hi' && translations.hi[key]) {
      return translations.hi[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
