import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {},
  hi: {
    "Dashboard": "डैशबोर्ड",
    "EVM Inventory": "ईवीएम लिस्ट",
    "Send EVM Batch": "ईवीएम भेजें",
    "Receive EVM Units": "ईवीएम प्राप्त करें",
    "User Management": "यूज़र मैनेजमेंट",
    "Reports & Analytics": "रिपोर्ट और विश्लेषण",
    "Search EVM Units": "ईवीएम खोजें",
    "Activity Logs": "लॉग देखें",
    "Logout Panel": "लॉगआउट",
    "Dashboard Overview": "डैशबोर्ड",
    "EVM Inventory System": "ईवीएम इन्वेंटरी",
    "Register EVM": "ईवीएम रजिस्टर करें",
    "Pending Receivables": "लंबित प्राप्तियां",
    "User Account Control": "यूज़र कंट्रोल",
    "System Activity Logs": "गतिविधि लॉग",
    "User Account Control System": "यूज़र कंट्रोल",
    "User Code": "यूज़र आईडी",
    "Full Name": "पूरा नाम",
    "Role": "भूमिका",
    "Jurisdiction": "अधिकार क्षेत्र",
    "Type": "प्रकार",
    "Account Status": "स्टेटस",
    "Last Login": "अंतिम लॉगिन",
    "Actions": "कार्रवाई",
    "Create Officer Account": "नया यूज़र बनाएं",
    "Reset Filters": "फ़िल्टर हटाएं",
    "Filter Users": "यूज़र फ़िल्टर करें",
    "Search Users": "यूज़र खोजें",
    "Search User ID or Name...": "आईडी या नाम खोजें...",
    "State": "राज्य",
    "District": "ज़िला",
    "Role type": "भूमिका प्रकार",
    "All Roles": "सभी भूमिकाएं",
    "All States": "सभी राज्य",
    "All Statuses": "सभी स्टेटस",
    "Choose District": "ज़िला चुनें",
    "Select State First": "पहले राज्य चुनें",
    "Save Modifications": "बदलाव सहेजें",
    "Cancel": "रद्द करें",
    "Security Password": "पासवर्ड",
    "Password": "पासवर्ड",
    "Sign In": "लॉगिन करें",
    "Confirm Password": "पासवर्ड कन्फर्म करें",
    "Confirm New Password": "नया पासवर्ड कन्फर्म करें",
    "Officer Role Type": "अधिकारी की भूमिका",
    "Username": "यूज़रनेम",
    "State Jurisdictional Allocation": "राज्य आवंटन",
    "District Allocation": "ज़िला आवंटन",
    "Officer Full Name": "पूरा नाम",
    "Edit Account": "खाता एडिट करें",
    "Save": "सहेजें",
    "Confirm Action": "कन्फर्म करें",
    "Confirm": "कन्फर्म",
    "Active": "सक्रिय",
    "Inactive": "निष्क्रिय",
    "State Officer": "राज्य अधिकारी",
    "District Officer": "ज़िला अधिकारी",
    "Permanent": "स्थायी",
    "Temporary": "अस्थायी",
    "Active Accounts": "सक्रिय खाते",
    "Deactivated Accounts": "निष्क्रिय खाते",
    "Search": "खोजें",
    "System Dashboard": "सिस्टम डैशबोर्ड",
    "Logged in as": "लॉगिन यूज़र:",
    "Sync Data": "डेटा सिंक करें",
    "Synchronizing systems...": "सिंक हो रहा है...",
    "Loading EVM database...": "डेटा लोड हो रहा है...",
    "System Sync Failure": "सिंक फेल",
    "Failed to fetch database information. Ensure the backend server is running and database schema is seeded.": "डेटाबेस से कनेक्ट नहीं हो सका। कृपया सर्वर और डेटाबेस चेक करें।",
    "Retry Sync": "दोबारा सिंक करें",
    "Total EVM Units": "कुल ईवीएम",
    "Receiving pending": "प्राप्ति लंबित",
    "Unit is already receiving pending.": "यूनिट पहले से ही प्राप्ति लंबित है।",
    "Currently receiving pending": "प्राप्ति लंबित",
    "No movements": "कोई हलचल नहीं",
    "moving": "प्राप्ति लंबित",
    "flagged": "गड़बड़ (फ्लैग)",
    "0 flagged": "0 गड़बड़",
    "Faulty / Repair": "खराब / मरम्मत",
    "Reported damaged/faulty units": "खराब/क्षतिग्रस्त ईवीएम",
    "EVM Operations panel": "ईवीएम संचालन",
    "Dispatch Consignment": "बैच भेजें",
    "Confirm Receipt": "प्राप्ति कन्फर्म करें",
    "Initiate a new physical transfer of units to another state or district warehouse.": "दूसरे राज्य या ज़िले में ईवीएम भेजने की प्रक्रिया शुरू करें।",
    "New Dispatch": "नया डिस्पैच",
    "Scan and register incoming units sent to your location. Check conditions on receipt.": "आने वाले ईवीएम स्कैन और रजिस्टर करें। प्राप्ति के समय स्थिति की जांच करें।",
    "Inventory Catalog": "इन्वेंटरी लिस्ट",
    "View allocation charts, search barcodes/QR codes, and inspect unit movement history.": "चार्ट देखें, बारकोड/क्यूआर कोड सर्च करें और ईवीएम का इतिहास देखें।",
    "View Inventory": "इन्वेंटरी देखें",
    "Recent Dispatch Batches": "हाल के डिस्पैच",
    "View Logs": "लॉग देखें",
    "Batch Code": "बैच कोड",
    "From Location": "कहां से",
    "To Destination": "कहां को",
    "Units": "यूनिट्स",
    "Dispatch Date": "भेजने की तारीख",
    "Status": "स्टेटस",
    "Pending Incoming Shipments": "आने वाले बैच",
    "Pending Incoming Consignments": "आने वाले बैच",
    "There are": "कुल",
    "batch(es) of EVM units currently receiving pending destined for your district or state. Review and process their receipt immediately upon physical arrival.": "ईवीएम बैच प्राप्ति लंबित हैं। आने पर तुरंत दर्ज करें।",
    "Go to Receipt Panel": "प्राप्ति दर्ज करें",
    "Origin": "उत्पत्ति",
    "Sent": "भेजा गया",
    "And": "और",
    "more. View All": "और देखें",
    "EVM Allocation by District": "ज़िलावार ईवीएम आवंटन",
    "No district allocation data available.": "कोई डेटा उपलब्ध नहीं है।",
    "EVM Inventory Status Allocation": "ईवीएम स्टेटस",
    "No status distribution data available.": "कोई डेटा उपलब्ध नहीं है।",
    "In Warehouse": "गोदाम में",
    "CU": "कंट्रोल यूनिट (CU)",
    "BU": "बैलेट यूनिट (BU)",
    "DMM": "डीएमएम (DMM)",
    "CU:": "कंट्रोल यूनिट (CU):",
    "BU:": "बैलेट यूनिट (BU):",
    "DMMs": "डीएमएम (DMM)",
    "DMMs:": "डीएमएम (DMM):",
    "Unit Code": "यूनिट कोड",
    "Manufacturer": "निर्माता",
    "Serial Number": "सीरियल नंबर",
    "Current Location": "वर्तमान स्थान",
    "Device Category Type": "डिवाइस टाइप",
    "Manufacturer Corporation": "निर्माता",
    "Manufacturing Year": "निर्माण वर्ष",
    "Unit Serial Number": "सीरियल नंबर",
    "Initial Warehouse / Storage Details": "प्रारंभिक गोदाम/भंडारण विवरण",
    "Register & Save Unit": "रजिस्टर और सेव करें",
    "ECI Headquarters": "ECI मुख्यालय",
    "Central Headquarters": "केंद्रीय मुख्यालय",
    "Government of India — Secure EVM Tracking portal.": "भारत सरकार — ईवीएम ट्रैकिंग पोर्टल।",
    "Access is audited. Unauthorized entries will be prosecuted under federal cyber security laws.": "सभी गतिविधियों का ऑडिट किया जाता है। अनधिकृत प्रवेश दंडनीय है।",
    "User Id": "यूज़र आईडी",
    "Remember this session": "लॉगिन याद रखें",
    "Verify & Authenticate": "वेरिफाई और लॉगिन करें",
    "EVM Lifecycle Management": "ईवीएम लाइफसाइकल",
    "EVM Inventory Management System": "ईवीएम इन्वेंटरी मैनेजमेंट",
    "Election Commission of India Portal": "ECI पोर्टल",
    "Madhya Pradesh State Election Commission": "मध्य प्रदेश राज्य निर्वाचन आयोग",
    "Madhya Pradesh State Election Commission — EVM Inventory Management System": "मध्य प्रदेश राज्य निर्वाचन आयोग — ईवीएम इन्वेंटरी मैनेजमेंट",
    "Authentication Failure:": "लॉगिन फेल:",
    "User ID must be at least 3 characters": "यूज़र आईडी कम से कम 3 अक्षरों की होनी चाहिए",
    "Password must be at least 6 characters": "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
    "Format: STATE_OFFICER_XX or DISTRICT_OFFICER_XX": "फॉर्मेट: STATE_OFFICER_XX या DISTRICT_OFFICER_XX",
    "Secure Access Gateway": "सुरक्षित लॉगिन",
    "EVM Barcode / QR Code": "ईवीएम बारकोड / क्यूआर कोड",
    "Assigned Storage Box (Capacity 10)": "स्टोरेज बॉक्स (क्षमता 10)",
    "Warehouse location Description": "गोदाम का विवरण",
    "Register & Add to Shipment": "रजिस्टर करें और जोड़ें",
    "Register & Add to consignment": "रजिस्टर करें और जोड़ें",
    "EVM Barcode / QR Code (Unit Code)": "ईवीएम बारकोड / क्यूआर कोड",
    "Unique barcode/QR text scanned from physical device labels.": "डिवाइस लेबल से स्कैन किया गया कोड।",
    "Physical factory serial stamp number (e.g. S-39281)": "सीरियल नंबर (जैसे S-39281)",
    "E.g. Room A, Shelf 2 or North District Strongroom": "जैसे कमरा A, शेल्फ 2 या स्ट्रांगरूम",
    "EVM Main": "ईवीएम मुख्य",
    "Inventory": "इन्वेंटरी",
    "Dispatches": "डिस्पैच",
    "Print Receipt": "रसीद प्रिंट करें",
    "Dispatch Another Batch": "एक और बैच भेजें",
    "Shipment Sent Successfully!": "शिपमेंट सफलतापूर्वक भेजा गया!",
    "Consignment Consumed & Dispatched Successfully!": "शिपमेंट सफलतापूर्वक भेजा गया!",
    "Expected Arrival": "अपेक्षित आगमन",
    "Officer Remarks": "अधिकारी की टिप्पणी",
    "Staged Inventory Summary": "तैयार इन्वेंटरी का सारांश",
    "Control Units (CU):": "कंट्रोल यूनिट (CU):",
    "Ballot Units (BU):": "बैलेट यूनिट (BU):",
    "DMMs:": "डीएमएम (DMM):",
    "Total Units:": "कुल यूनिट:",
    "Shipment Details": "शिपमेंट विवरण",
    "Consignment Details": "शिपमेंट विवरण",
    "Shipping From": "प्रेषक स्थान",
    "Shipping To": "प्राप्तकर्ता स्थान",
    "Transit Remarks / Notes": "ट्रांजिट नोट्स",
    "All Districts": "सभी जिले",
    "Next: Destination": "अगला: गंतव्य",
    "New Security Password": "नया सुरक्षा पासवर्ड",
    "Leave empty to retain current password": "वर्तमान पासवर्ड बनाए रखने के लिए खाली छोड़ें",
    "Edit Officer Account": "अधिकारी खाता एडिट करें",
    "Save Changes": "सेव करें",
    "Create": "बनाएं",
    "Clear All": "सभी साफ करें",
    "Log Out": "लॉग आउट",
    "Search results for": "खोज परिणाम",
    "No results found": "कोई परिणाम नहीं मिला",
    "Timestamp": "समय",
    "Performed By": "किसने किया",
    "Security Action": "एक्शन",
    "Entity Impacted": "प्रभावित चीज़",
    "IP Address": "IP एड्रेस",
    "Inspect Payload": "पेलोड देखें",
    "IN_WAREHOUSE": "गोदाम में",
    "IN_TRANSIT": "प्राप्ति लंबित",
    "CONTROL_UNIT": "कंट्रोल यूनिट (CU)",
    "BALLOT_UNIT": "मतपत्र इकाई (BU)",
    "DMM": "डीएमएम (DMM)",
    "ADMIN": "सिस्टम एडमिन",
    "STATE_OFFICER": "राज्य अधिकारी",
    "DISTRICT_OFFICER": "ज़िला अधिकारी",
    "System Administrator": "सिस्टम एडमिन",
    "STATE OFFICER": "राज्य अधिकारी",
    "DISTRICT OFFICER": "ज़िला अधिकारी",
    "Admin": "एडमिन",
    "EVM": "ईवीएम",
    "System": "प्रणाली",
    "Secure Portal": "सुरक्षित पोर्टल",
    "Connecting to EVM database...": "कनेक्ट हो रहा है...",
    "Incoming Shipment Receipts": "आने वाले शिपमेंट",
    "Incoming Consignment Receipts": "आने वाले शिपमेंट",
    "Confirm and inspect device packages sent to your warehouse location.": "अपने स्थान पर भेजे गए डिवाइस पैकेजों की जांच करें।",
    "Acknowledge and inspect physical device packages sent to your warehouse custody.": "अपने स्थान पर भेजे गए डिवाइस पैकेजों की जांच करें।",
    "Refresh Shipments": "रीफ्रेश करें",
    "Refresh Consignments": "रीफ्रेश करें",
    "All Shipments Received": "सभी शिपमेंट प्राप्त हुए",
    "All Shipments Acknowledged": "सभी शिपमेंट प्राप्त हुए",
    "There are currently no pending receiving pending batches allocated for your state or district warehouse location.": "वर्तमान में कोई लंबित बैच प्राप्ति के लिए नहीं हैं।",
    "There are currently no pending receiving pending batches allocated for your state or district warehouse custody.": "वर्तमान में कोई लंबित बैच प्राप्ति के लिए नहीं हैं।",
    "Sent Date": "भेजने की तारीख",
    "Items Quantity": "मात्रा",
    "View Receipt Details": "रसीद विवरण देखें",
    "Details": "विवरण",
    "Acknowledge Consignment": "प्राप्ति दर्ज करें",
    "Shipping Origin": "कहां से भेजा",
    "Dispatched Date": "भेजने की तारीख",
    "Mark All Received": "सभी प्राप्त मार्क करें",
    "Mark All Missing": "सभी गायब मार्क करें",
    "Mark All Sealed Good": "सभी सही मार्क करें",
    "Recd.": "प्राप्त",
    "Condition on Receipt": "प्राप्ति पर स्थिति",
    "Remarks": "टिप्पणी",
    "E.g. Lock seal intact": "जैसे लॉक सील ठीक है",
    "Security Disclaimer": "सुरक्षा अस्वीकरण",
    "Submitting receipt changes the status of successfully checked devices to IN_WAREHOUSE at your location. Missing units are locked immediately and flagged for investigation.": "प्राप्ति दर्ज करने से ईवीएम गोदाम में (IN_WAREHOUSE) हो जाएंगे। गायब ईवीएम तुरंत लॉक हो जाएंगे।",
    "Log Batch Receipt": "प्राप्ति दर्ज करें",
    "Good (Sealed)": "सही (सील बंद)",
    "Damaged (Broken Seal)": "खराब (टूटी सील)",
    "Faulty (Electronic Issue)": "खराब (इलेक्ट्रॉनिक समस्या)",
    "Retrieving shipping details...": "शिपिंग विवरण लोड हो रहा है...",
    "Batch Record Not Found": "बैच रिकॉर्ड नहीं मिला",
    "The requested dispatch batch or receipt code does not exist in ECI records.": "अनुरोधित डिस्पैच बैच रिकॉर्ड में नहीं है।",
    "Back to Dashboard": "डैशबोर्ड पर जाएं",
    "Sl No.": "क्र.सं.",
    "Box Number": "बॉक्स नंबर",
    "Not Received Yet": "अभी प्राप्त नहीं हुआ",
    "MISSING": "गायब",
    "Shipment Dispatch Details": "शिपमेंट विवरण",
    "Consignment Dispatch Details": "शिपमेंट विवरण",
    "Cancel Dispatch": "रद्द करें",
    "Cancel Consignment": "रद्द करें",
    "Shipping Summary": "शिपिंग सारांश",
    "By": "द्वारा",
    "Destination Warehouse": "गंतव्य गोदाम",
    "Received by": "किसने प्राप्त किया",
    "Timeline Details": "टाइमलाइन विवरण",
    "Arrival": "आगमन",
    "Custodian Remarks": "टिप्पणी",
    "Dispatched Device Items List": "भेजे गए ईवीएम की सूची",
    "Receipt Details": "रसीद विवरण",
    "No Units Linked": "कोई यूनिट लिंक नहीं है",
    "This batch has no registered units. Check database integrity.": "इस बैच में कोई यूनिट्स पंजीकृत नहीं हैं।",
    "Cancel Dispatch consignment": "डिस्पैच रद्द करें",
    "Warning": "चेतावनी",
    "Cancelling a shipment cannot be undone. All devices in this shipment will automatically return to the sender warehouse location.": "शिपमेंट रद्द करना बदला नहीं जा सकता। सभी डिवाइस भेजने वाले के पास वापस चले जाएंगे।",
    "Cancelling a consignment is irreversible. All associated devices (CUs, BUs) will be automatically returned to the shipping warehouse custody.": "शिपमेंट रद्द करना बदला नहीं जा सकता। सभी डिवाइस भेजने वाले के पास वापस चले जाएंगे।",
    "Cancellation Reason / Audit notes": "रद्द करने का कारण",
    "E.g. Security convoy rescheduled, typo in destination warehouse state, etc.": "जैसे सुरक्षा कारण, गलत गंतव्य, आदि।",
    "Back": "पीछे",
    "Abort & Cancel Dispatch": "डिस्पैच रद्द करें",
    "Register Scanned Device": "स्कैन किया हुआ डिवाइस रजिस्टर करें",
    "EVM Not Registered": "ईवीएम पंजीकृत नहीं है",
    "was not found in the inventory system database. Please enter manufacturer details to add it now.": "डेटाबेस में नहीं मिला। कृपया इसे जोड़ने के लिए विवरण दर्ज करें।",
    "Fetching device details and lifecycle history...": "विवरण और इतिहास लोड हो रहा है...",
    "Back to Inventory": "इन्वेंटरी पर जाएं",
    "Sync Device Details": "विवरण सिंक करें",
    "No tracking events recorded.": "कोई इतिहास रिकॉर्ड नहीं है।",
    "Audit inventory records, tracking histories, and logistics transaction logs.": "इन्वेंटरी रिकॉर्ड, ट्रैकिंग इतिहास और रसद गतिविधि लॉग का ऑडिट करें।",
    "Inventory Location": "इन्वेंटरी स्थान",
    "Inventory Custody": "इन्वेंटरी स्थान",
    "Dispatch History": "डिस्पैच इतिहास",
    "Movement Timeline": "टाइमलाइन",
    "State Location": "राज्य स्थान",
    "District Location": "ज़िला स्थान",
    "District Custody": "ज़िला स्थान",
    "State Pool": "राज्य पूल",
    "Inventory Location Summary Report": "इन्वेंटरी स्थान सारांश रिपोर्ट",
    "Inventory Custody Summary Report": "इन्वेंटरी स्थान सारांश रिपोर्ट",
    "Export CSV": "CSV एक्सपोर्ट",
    "No Inventory Summaries Found": "कोई सारांश नहीं मिला",
    "Check if data has been registered or seeded in the database.": "चेक करें कि डेटाबेस में डेटा है या नहीं।",
    "Origin Location": "मूल स्थान",
    "Units Quant": "मात्रा",
    "Shipment History Logs": "शिपमेंट इतिहास",
    "Consignment Dispatch History Logs": "शिपमेंट इतिहास",
    "No Dispatch History Logs Found": "कोई इतिहास नहीं मिला",
    "Log Date": "तारीख",
    "Device Type": "डिवाइस टाइप",
    "Lifecycle Action": "गतिविधि",
    "Triggered By": "किसने किया",
    "Device Movement Transaction Logs": "डिवाइस गतिविधि लॉग",
    "No Movement Transaction Logs Recorded": "कोई गतिविधि लॉग नहीं है",
    "Showing page": "पेज",
    "of": "का",
    "System Audit Trail Logs": "सिस्टम ऑडिट लॉग",
    "Immutable log of all user logins, credential changes, registry modifications, and dispatches.": "यूज़र लॉगिन, पासवर्ड बदलाव और गतिविधियों का लॉग।",
    "Sync Log Files": "लॉग सिंक करें",
    "Filter Logs": "लॉग फ़िल्टर",
    "Search Performed By (User ID/Name) or Entity ID...": "यूज़र आईडी/नाम या इकाई आईडी खोजें...",
    "Log Action Type": "एक्शन टाइप",
    "All Log Actions": "सभी एक्शन",
    "No Audit Logs Found": "कोई ऑडिट लॉग नहीं मिला",
    "Try resetting your filters or checks systems connections.": "फ़िल्टर हटाएं या सिस्टम कनेक्शन चेक करें।",
    "Inspect Security Audit payload": "सुरक्षा ऑडिट पेलोड देखें",
    "Original State (Old Values)": "पुरानी स्थिति",
    "No original values captured (Create action)": "कोई पुराना विवरण नहीं (निर्माण कार्य)",
    "Modified State (New Values)": "नई स्थिति",
    "No replacement values captured (Delete action)": "कोई नया विवरण नहीं (हटाने का कार्य)",
    "Close Inspector": "बंद करें",
    "Search Inventory": "इन्वेंटरी खोजें",
    "View History": "इतिहास देखें",
    "State Officer (Read/Write State)": "राज्य अधिकारी",
    "District Officer (Read/Write District)": "ज़िला अधिकारी",
    "Unique login ID (e.g. MH_SO_01, USER_CENTRAL)": "अद्वितीय लॉगिन आईडी (जैसे MH_SO_01)",
    "State officers bypass districts": "राज्य अधिकारी जिला बाईपास कर सकते हैं",
    "Central ECI": "केंद्रीय ECI",
    "Role Assigned": "भूमिका आवंटित",
    "Password Reset Option": "पासवर्ड रीसेट विकल्प",
    "Leave both password fields blank unless you explicitly want to override the security credential password for this officer.": "यदि आप पासवर्ड बदलना नहीं चाहते, तो इसे खाली छोड़ दें।",
    "Min 8 chars, 1 upper, 1 number, 1 special symbol.": "कम से कम 8 अक्षर, 1 बड़ा अक्षर, 1 संख्या और 1 विशेष चिन्ह।",
    "Current Custody": "वर्तमान स्थान",
    "registered and added to consignment": "पंजीकृत और शिपमेंट में जोड़ा गया",
    "registered and added to shipment": "पंजीकृत और शिपमेंट में जोड़ा गया",
    "Loading consignment items from EVM database...": "डेटाबेस से शिपमेंट लोड हो रहा है...",
    "Loading shipment items from EVM database...": "डेटाबेस से शिपमेंट लोड हो रहा है...",
    "EVM Shipment Receipt": "ईवीएम शिपमेंट रसीद",
    "Inspect Activity Log Details": "गतिविधि लॉग विवरण",
    "Reports & Analytics Portal": "रिपोर्ट और विश्लेषण",
    "Audit inventory records, tracking histories, and transaction logs.": "इन्वेंटरी रिकॉर्ड, ट्रैकिंग इतिहास और लेनदेन लॉग का ऑडिट करें।",
    "Device Movement History Logs": "डिवाइस गतिविधि लॉग",
    "total logs": "कुल लॉग",
    "Send EVM": "भेजें (डिस्पैच)",
    "Receive EVM": "प्राप्त करें (रसीद)",
    "User Control": "यूज़र कंट्रोल",
    "Global Search": "वैश्विक खोज",
    "Register New EVM": "नया ईवीएम जोड़ें",
    "EVM Lifecycle Details": "ईवीएम विवरण",
    "Dispatch Batch Summary": "डिस्पैच सारांश",
    "EVM Management": "ईवीएम प्रबंधन",
    "Pending": "लंबित",
    "Received": "प्राप्त",
    "Partial": "आंशिक",
    "Cancelled": "रद्द",
    "Control Unit": "कंट्रोल यूनिट (CU)",
    "Ballot Unit": "मतपत्र इकाई (BU)",
    "DMM": "डीएमएम (DMM)",
    "Dispatched": "भेजा गया",
    "Missing": "गायब",
    "Damaged": "क्षतिग्रस्त",
    "Good": "सही",
    "Global Database Lookup": "वैश्विक खोज",
    "Query across the unified registry: look up device unit barcodes, manufacturer serial stamps, or logistics dispatch batch codes.": "बारकोड, सीरियल नंबर या बैच कोड खोजें।",
    "Enter 3+ characters to search unit codes, serials, batch codes...": "खोजने के लिए 3 या अधिक अक्षर दर्ज करें...",
    "Querying ECI directories...": "खोजा जा रहा है...",
    "Lookup Error": "खोज त्रुटि",
    "Failed to perform global search queries. Verify if search API services are fully operational.": "वैश्विक खोज करने में विफल।",
    "No Records Found": "कोई रिकॉर्ड नहीं मिला",
    "No matching registries found for query": "कोई मिलान रिकॉर्ड नहीं मिला",
    "Check spelling or prefix identifiers.": "स्पेलिंग चेक करें।",
    "Matching EVM Device Units": "मिलान ईवीएम इकाइयां",
    "Serial:": "सीरियल:",
    "Custody:": "स्थान:",
    "Matching Dispatch Batches": "मिलान डिस्पैच बैच",
    "Flow:": "प्रवाह:",
    "Sent:": "भेजा गया:",
    "Ballot Unit (BU)": "मतपत्र इकाई (BU)",
    "DMM": "डीएमएम (DMM)",
    "Full registry of all Electronic Voting Machine devices allocated across India.": "ईवीएम की पूर्ण सूची।",
    "Filter Catalog": "फ़िल्टर",
    "Search Unit Code / Serial No...": "यूनिट कोड / सीरियल नंबर खोजें...",
    "All Types": "सभी प्रकार",
    "No EVM Units Found": "कोई ईवीएम इकाई नहीं मिली",
    "Try tweaking your filter conditions, resetting, or verifying code format.": "फ़िल्टर की शर्तों को बदलने या रीसेट करने का प्रयास करें।",
    "total units": "कुल इकाइयां",
    "New EVM unit registered successfully": "नई ईवीएम इकाई पंजीकृत हुई",
    "Failed to register EVM unit. It may already exist.": "ईवीएम पंजीकृत करने में विफल।",
    "Insert a new Electronic Voting Machine unit record into the central ECI system.": "एक नया ईवीएम रिकॉर्ड दर्ज करें।",
    "Notice": "सूचना",
    "Registered units are assigned to the current user's state/district location by default. This registry update will be logged under audit trail.": "पंजीकृत इकाइयां वर्तमान स्थान पर आवंटित हो जाती हैं।",
    "Scan using camera": "कैमरे से स्कैन करें",
    "Box": "बॉक्स",
    "Box Number": "बॉक्स नंबर",
    "Storage Box": "स्टोरेज बॉक्स",
    "Box Summary": "बॉक्स सारांश",
    "Storage Box Summary Report": "स्टोरेज बॉक्स सारांश रिपोर्ट",
    "Units in Box": "बॉक्स में इकाइयां",
    "Capacity": "क्षमता",
    "Fill Status": "भरने की स्थिति",
    "Full": "भरा हुआ",
    "Filling": "भर रहा है",
    "Available": "उपलब्ध",
    "No Box Data Found": "कोई बॉक्स डेटा नहीं मिला",
    "Register EVM units to see box allocation data.": "बॉक्स आवंटन डेटा देखने के लिए ईवीएम दर्ज करें।",
    "Scan EVM Barcode / QR Code": "ईवीएम बारकोड / क्यूआर कोड स्कैन करें",
    "Align the EVM unit barcode or QR code sticker inside the scanner frame below.": "ईवीएम बारकोड या क्यूआर कोड स्कैनर फ्रेम के भीतर रखें।",
    "Successfully scanned unit code": "कोड सफलतापूर्वक स्कैन किया गया",
    "Dispatch batch cancelled successfully": "डिस्पैच सफलतापूर्वक रद्द हुआ",
    "Failed to cancel dispatch batch": "डिस्पैच रद्द करने में विफल",
    "Please enter a cancellation reason": "कृपया रद्द करने का कारण दर्ज करें",
    "Receipt Remarks": "प्राप्ति टिप्पणी",
    "Sync": "सिंक",
    "Origin Warehouse": "मूल गोदाम",
    "Expected": "अपेक्षित",
    "unit(s)": "इकाइयां",
    "Send EVM units between warehouses.": "गोदामों के बीच ईवीएम भेजें।",
    "1. Scan Units": "1. इकाइयाँ स्कैन करें",
    "2. Destination": "2. गंतव्य",
    "3. Receipt": "3. रसीद",
    "Scan Barcode or QR Code": "बारकोड या क्यूआर कोड स्कैन करें",
    "Type Unit Code": "यूनिट कोड लिखें",
    "Enter Unit Code (e.g. CU-192A)...": "यूनिट कोड दर्ज करें (जैसे CU-192A)...",
    "Stage": "स्टेज करें",
    "Units List": "इकाइयों की सूची",
    "unit(s) ready": "इकाइयां तैयार",
    "Clear Queue": "कतार साफ करें",
    "EVM List is Empty": "ईवीएम सूची खाली है",
    "Scan EVM barcode or type unit codes to add them to this shipping batch.": "ईवीएम बारकोड स्कैन करें या यूनिट कोड दर्ज करें।",
    "Summary": "सारांश",
    "Next: Select Destination": "आगे: गंतव्य चुनें",
    "Select Destination & Details": "गंतव्य और विवरण",
    "Shipping From Location": "प्रेषक का स्थान",
    "Destination State": "गंतव्य राज्य",
    "Select State": "राज्य चुनें",
    "Destination District": "गंतव्य ज़िला",
    "Select District": "ज़िला चुनें",
    "Expected Arrival Date": "अपेक्षित आगमन तारीख",
    "Shipping Notes": "शिपिंग नोट्स",
    "E.g. Vehicle number, remarks...": "जैसे वाहन संख्या, टिप्पणी...",
    "Back to Scanner": "स्कैनर पर वापस जाएं",
    "Confirm & Create Receipt": "पुष्टि करें और रसीद बनाएं",
    "EVM Batch Sent Successfully!": "ईवीएम बैच भेजा गया!",
    "Batch code": "बैच कोड",
    "has been written. Print and sign the receipt before shipping.": "लिखा गया है। प्रेषण से पहले रसीद प्रिंट और हस्ताक्षर करें।",
    "Send Another Batch": "एक और बैच भेजें",
    "Receipt Preview": "रसीद पूर्वावलोकन",
    "Unit": "इकाई",
    "No arrival date specified": "कोई तारीख निर्दिष्ट नहीं",
    "Failed to register EVM unit.": "ईवीएम इकाई को पंजीकृत करने में विफल।",
    "Unit is already added to this batch": "इकाई पहले से ही इस बैच में जोड़ी जा चुकी है",
    "The unit code": "यूनिट कोड",
    "Warehouse storage spot (e.g. Room A, Shelf 2 or North District Strongroom)": "भंडारण स्थान (जैसे कमरा A, शेल्फ 2 या स्ट्रांगरूम)",
    "Inspect and confirm EVM units sent to your location.": "प्राप्त ईवीएम का निरीक्षण और पुष्टि करें।",
    "Refresh List": "सूची रीफ्रेश करें",
    "There are no pending shipments for your location.": "कोई लंबित शिपमेंट नहीं है।",
    "Go to Dashboard": "डैशबोर्ड पर जाएं",
    "Total Units": "कुल इकाइयां",
    "View Receipt": "रसीद देखें",
    "Batch receipt logged and registered in inventory": "प्राप्ति दर्ज हुई और इन्वेंटरी में शामिल हुआ",
    "Failed to log batch receipt": "प्राप्ति दर्ज करने में विफल",
    "You are flagging": "आप चिह्नित कर रहे हैं",
    "units as MISSING. This triggers an immediate security alert. Continue?": "इकाइयों को गायब (MISSING) मार्क कर रहे हैं। क्या आप जारी रखना चाहते हैं?",
    "Control Units (CU)": "नियंत्रण इकाइयां (CU)",
    "Ballot Units (BU)": "मतपत्र इकाइयां (BU)",
    "Destination": "गंतव्य",
    "Date Dispatched": "भेजने की तारीख",
    "Actual Arrival": "वास्तविक आगमन",
    "To Location": "प्राप्तकर्ता स्थान",
    "Officer": "अधिकारी",
    "Never": "कभी नहीं",
    "Permanent Account": "स्थायी खाता",
    "Temporary Account": "अस्थायी खाता",
    "Manage officer accounts and system access.": "अधिकारी खातों और सिस्टम पहुंच का प्रबंधन करें।",
    "No Officers Registered": "कोई अधिकारी पंजीकृत नहीं है",
    "Try resetting your filter parameters or checking connection.": "फ़िल्टर मापदंडों को रीसेट करने का प्रयास करें।",
    "total accounts": "कुल खाते",
    "Deactivate Officer Account?": "अधिकारी खाता निष्क्रिय करें?",
    "Activate Officer Account?": "अधिकारी खाता सक्रिय करें?",
    "Are you sure you want to": "क्या आप चाहते हैं",
    "DEACTIVATE": "निष्क्रिय करना",
    "ACTIVATE": "सक्रिय करना",
    "account login ID:": "लॉगिन आईडी:",
    "All system credentials for this user will be": "इस उपयोगकर्ता के क्रेडेंशियल होंगे",
    "suspended immediately": "निलंबित",
    "re-enabled": "पुनः सक्रिय",
    "Hold barcode steady inside frame": "फ्रेम के भीतर बारकोड को रखें",
    "Retry Camera": "कैमरा पुनः प्रयास करें",
    "Last scan:": "अंतिम स्कैन:",
    "Mute scan sound": "आवाज बंद करें",
    "Unmute scan sound": "आवाज चालू करें",
    "Type Code": "कोड लिखें",
    "Enter Unit Code Manually": "यूनिट कोड दर्ज करें",
    "Add Code": "जोड़ें",
    "All rights reserved.": "सर्वाधिकार सुरक्षित।",
    "Resource Entry Not Found": "प्रविष्टि नहीं मिली",
    "The directory path or registry segment you requested does not exist or has been archived.": "अनुरोधित पृष्ठ या रिकॉर्ड उपलब्ध नहीं है।",
    "Return to Dashboard": "डैशबोर्ड पर जाएं",
    "Return to Login": "लॉगिन पर जाएं",
    "Go Back": "पीछे जाएं",
    "Madhya Pradesh State Election Commission Portal • 404 Error Log Generated": "मध्य प्रदेश राज्य निर्वाचन आयोग पोर्टल • 404 त्रुटि"
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('evm_language') || 'en';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('evm_language', lang);
  };

  const t = (key) => {
    if (!key) return '';
    if (language === 'hi' && translations.hi[key]) {
      return translations.hi[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
